In [1]:
import numpy as np
data = np.random.rand(2,3)

In [3]:
data

array([[0.55482891, 0.49619581, 0.09077112],
       [0.53906579, 0.13048401, 0.65565886]])

In [5]:
data * 10

array([[5.54828907, 4.96195808, 0.90771115],
       [5.39065794, 1.30484013, 6.55658857]])

In [7]:
data + data

array([[1.10965781, 0.99239162, 0.18154223],
       [1.07813159, 0.26096803, 1.31131771]])

In [9]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8,  0, 1]
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4], [5,6,7,8,]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype
arr2.dtype

dtype('int32')

In [27]:
np.zeros(10).shape

(10,)

In [30]:
np.zeros((3, 6)).shape

(3, 6)

In [34]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [38]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.ones((2,3)).dtype

dtype('float64')

In [56]:
print(np.ones_like((2,3)))

[1 1]


In [58]:
np.empty(np.ones((2,3)))

TypeError: only integer scalar arrays can be converted to a scalar index

In [66]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [67]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [69]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [71]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [74]:
arr2.dtype

dtype('int32')

In [79]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [80]:
arr.dtype

dtype('int64')

In [83]:
float_arr = arr.astype(np.float64)

In [86]:
float_arr

array([1., 2., 3., 4., 5.])

In [88]:
float_arr.astype(np.int32)

array([1, 2, 3, 4, 5])

In [97]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [98]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [101]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [102]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [104]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [106]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [108]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.empty_like(arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [113]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [115]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [116]:
arr = np.arange(10)

In [118]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
arr[5]

5

In [122]:
arr[5:8]

array([5, 6, 7])

In [124]:
arr[5:8]

array([5, 6, 7])

In [127]:
arr[5:8] = 122

In [129]:
arr

array([  0,   1,   2,   3,   4, 122, 122, 122,   8,   9])

In [132]:
arr_slice = arr[5:8]
arr_slice

array([122, 122, 122])

In [135]:
arr_slice[:] = 64

In [137]:
arr_slice

array([64, 64, 64])

In [139]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [140]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [144]:
arr2d[2]

array([7, 8, 9])

In [146]:
arr2d[0][2]z

SyntaxError: invalid syntax (<ipython-input-146-17366356810f>, line 1)

In [172]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [173]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [174]:
arr3d[0][0]

array([1, 2, 3])

In [175]:
old_values = arr3d[0].copy()

In [176]:
arr3d[0] = 42

In [177]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [178]:
arr3d[0] = old_values

In [179]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [180]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [181]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [182]:
arr3d[0][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
arr3d[1,0]

array([7, 8, 9])

In [187]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [194]:
# 3 x 3
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
arr2d[1, :2]

array([4, 5])

In [197]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [199]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [200]:
data = np.random.randn(7, 4)

In [202]:
data

array([[ 1.37526047,  0.1515802 ,  0.44363317, -0.7003571 ],
       [-0.57513419,  0.67445373,  0.89862707, -0.29245501],
       [ 0.41951005,  1.49629355, -0.57711032, -1.05396978],
       [ 1.19746609,  0.95608755,  1.4263602 , -0.83187219],
       [ 0.84853534, -1.07062183,  1.37149821,  1.83333262],
       [ 0.71167018, -0.83634308, -0.87364097,  0.075956  ],
       [-0.16140373,  0.05140718,  0.89365572, -0.22157727]])

In [204]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [213]:
data[names == 'Bob']

array([[ 1.37526047,  0.1515802 ,  0.44363317, -0.7003571 ],
       [ 1.19746609,  0.95608755,  1.4263602 , -0.83187219]])

In [218]:
# 혼동 될 소지가 매우크다.
data[names == 'Bob', 2: ]

array([[ 0.44363317, -0.7003571 ],
       [ 1.4263602 , -0.83187219]])

In [223]:
data[~(names == 'Bob')]

array([[-0.57513419,  0.67445373,  0.89862707, -0.29245501],
       [ 0.41951005,  1.49629355, -0.57711032, -1.05396978],
       [ 0.84853534, -1.07062183,  1.37149821,  1.83333262],
       [ 0.71167018, -0.83634308, -0.87364097,  0.075956  ],
       [-0.16140373,  0.05140718,  0.89365572, -0.22157727]])

In [221]:
data[names == 'Bob']


array([[ 1.37526047,  0.1515802 ,  0.44363317, -0.7003571 ],
       [ 1.19746609,  0.95608755,  1.4263602 , -0.83187219]])

In [225]:
data[data < 0] =0

In [227]:
data

array([[1.37526047, 0.1515802 , 0.44363317, 0.        ],
       [0.        , 0.67445373, 0.89862707, 0.        ],
       [0.41951005, 1.49629355, 0.        , 0.        ],
       [1.19746609, 0.95608755, 1.4263602 , 0.        ],
       [0.84853534, 0.        , 1.37149821, 1.83333262],
       [0.71167018, 0.        , 0.        , 0.075956  ],
       [0.        , 0.05140718, 0.89365572, 0.        ]])

In [231]:
data[names != 'Joe'] = 7

In [232]:
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [234]:
arr = np.empty((8, 4))

In [236]:
arr

array([[1.53005776e-311, 1.53003352e-311, 1.53005882e-311,
        1.53003587e-311],
       [1.53005917e-311, 1.53005828e-311, 1.53005909e-311,
        1.53003338e-311],
       [1.53003380e-311, 1.53005917e-311, 1.53003605e-311,
        1.53005917e-311],
       [1.53005917e-311, 1.53005917e-311, 1.53005917e-311,
        1.53003381e-311],
       [1.53005917e-311, 1.53003354e-311, 1.53005917e-311,
        1.53005917e-311],
       [1.53005843e-311, 1.53003437e-311, 1.53005841e-311,
        1.53005917e-311],
       [1.53005917e-311, 1.53003800e-311, 1.53005917e-311,
        1.53003375e-311],
       [1.53003556e-311, 1.53003352e-311, 1.53005917e-311,
        1.53005917e-311]])

In [238]:
for i in range(8):
    arr[i] = i

In [240]:
arr 

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [244]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [246]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [250]:
arr = np.arange(32)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [254]:
arr.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [257]:
np.arange(31).reshape((8,4))

ValueError: cannot reshape array of size 31 into shape (8,4)

In [259]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [261]:
arr = arr.reshape((8,4))

In [263]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [269]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [271]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [274]:
# arr[]
np.ix_([1,5,7,2], [0,3,1,2])

(array([[1],
        [5],
        [7],
        [2]]), array([[0, 3, 1, 2]]))

In [275]:
arr = np.arange(15).reshape((3,5))

In [277]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [282]:
arr.T.shape

(5, 3)

In [287]:
arr = np.random.randn(6, 3)

In [291]:
# dot operation (내적)
np.dot(arr.T, arr)

array([[5.42036983, 3.15008736, 3.03628744],
       [3.15008736, 7.09147907, 4.5705083 ],
       [3.03628744, 4.5705083 , 3.50978022]])

In [294]:
  ~np.array([True, False])

array([False,  True])

In [295]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

1.19 s ± 77.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [297]:
%timeit np.random.normal(size=N)

36.9 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
